Repository ns1-terraform/terraform-provider-ns1, pull requests merged in 2019-09, with the labels that each got.

#64 randomize zone name in acc tests
  CHANGELOG.md
  ns1/data_source_zone_test.go
  ns1/resource_zone.go
  ns1/resource_zone_test.go
Labels: size/M

#66 Address complaints from golint
  ns1/config.go
  ns1/provider.go
  ns1/resource_record.go
  ns1/string_enum.go
Labels: size/XS

#67 Add Request Logging
  ns1/config.go
Labels: size/M

#68 Record: ignore the order of the locations provided in the regions blocks
  ns1/resource_record.go
  ns1/resource_record_test.go
Labels: size/S

#69 Lint and docs
  ns1/resource_record.go
  ns1/resource_record_test.go
  website/docs/r/record.html.markdown
Labels: documentation, size/M

#65 INT-24: support outgoing transfer aka primary zone
  go.mod
  go.sum
  ns1/data_source_zone.go
  ns1/data_source_zone_test.go
  ns1/resource_record_test.go
  ns1/resource_zone.go
  ns1/resource_zone_test.go
  ns1/test_funcs.go
  vendor/github.com/hashicorp/terraform/helper/structure/expand_json.go
  vendor/github.com/hashicorp/terraform/helper/structure/flatten_json.go
  vendor/github.com/hashicorp/terraform/helper/structure/normalize_json.go
  vendor/github.com/hashicorp/terraform/helper/structure/suppress_json_diff.go
  vendor/github.com/hashicorp/terraform/helper/validation/validation.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/LICENSE
  vendor/gopkg.in/yaml.v2/LICENSE.libyaml
  vendor/gopkg.in/yaml.v2/NOTICE
  vendor/gopkg.in/yaml.v2/README.md
  vendor/gopkg.in/yaml.v2/apic.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/emitterc.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gopkg.in/yaml.v2/parserc.go
  vendor/gopkg.in/yaml.v2/readerc.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/sorter.go
  vendor/gopkg.in/yaml.v2/writerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
  vendor/gopkg.in/yaml.v2/yamlprivateh.go
  vendor/modules.txt
  website/docs/d/zone.html.markdown
  website/docs/r/zone.html.markdown
Labels: dependencies, documentation, size/XXL

#71 BUGFIX: disallow setting SOA fields on secondary zones
  ns1/resource_zone.go
  ns1/resource_zone_test.go
  website/docs/r/zone.html.markdown
Labels: documentation, size/S

#70 INT-43 support toggling DNSSEC on zones
  README.md
  go.mod
  go.sum
  ns1/data_source_zone.go
  ns1/data_source_zone_test.go
  ns1/resource_zone.go
  ns1/resource_zone_test.go
  vendor/gopkg.in/ns1/ns1-go.v2/rest/client.go
  vendor/gopkg.in/ns1/ns1-go.v2/rest/dnssec.go
  vendor/gopkg.in/ns1/ns1-go.v2/rest/model/dns/dnssec.go
  vendor/gopkg.in/ns1/ns1-go.v2/rest/model/dns/zone.go
  vendor/modules.txt
  website/docs/d/zone.html.markdown
  website/docs/index.html.markdown
  website/docs/r/zone.html.markdown
Labels: dependencies, documentation, size/XL
