Repository ns1-terraform/terraform-provider-ns1, pull requests merged in 2019-11, with the labels that each got.

#88 Add config option to use an alternate rate limit strategy
  go.mod
  go.sum
  ns1/config.go
  ns1/provider.go
  vendor/gopkg.in/ns1/ns1-go.v2/rest/client.go
  vendor/gopkg.in/ns1/ns1-go.v2/rest/headers.go
  vendor/gopkg.in/ns1/ns1-go.v2/rest/zone.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/modules.txt
  website/docs/index.html.markdown
Labels: dependencies, documentation, size/L

#89 Minor Documentation and Makefile fixes
  GNUmakefile
  README.md
Labels: size/XS

#93 Change Error strings to comply with golang standard.
  ns1/data_source_dnssec_test.go
  ns1/resource_datafeed_test.go
  ns1/resource_datasource_test.go
  ns1/resource_monitoringjob_test.go
  ns1/resource_notifylist_test.go
  ns1/resource_record_test.go
  ns1/resource_user_test.go
  ns1/resource_zone_test.go
Labels: size/M
