Repository ns1-terraform/terraform-provider-ns1, pull requests merged in 2019-10, with the labels that each got.

#72 DNSSEC data source
  ns1/data_source_dnssec.go
  ns1/data_source_dnssec_test.go
  ns1/provider.go
  website/docs/d/dnssec.html.markdown
  website/ns1.erb
Labels: documentation, size/XL

#73 cleanup: rename/reuse "zone" funcs
  ns1/data_source_zone.go
  ns1/resource_zone.go
Labels: size/S

#74 INT-49: bump version of ns1 SDK
  go.mod
  go.sum
  vendor/gopkg.in/ns1/ns1-go.v2/rest/client.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/modules.txt
Labels: dependencies, size/M

#75 INT-62: Allow secondary zones to become primary in place
  go.mod
  go.sum
  ns1/data_source_zone_test.go
  ns1/resource_zone.go
  ns1/resource_zone_test.go
  ns1/test_funcs.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/compose.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/computed.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/condition.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/doc.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/force_new.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/validate.go
  vendor/modules.txt
  website/docs/r/zone.html.markdown
Labels: dependencies, documentation, size/XL

#76 bump go version for CI and README (1.11+ to 1.12+)
  .travis.yml
  README.md
Labels: size/XS

#82 INT-24: secondaries port and notify defaults
  ns1/resource_zone.go
Labels: size/XS

#80 ns1_zone: add a new 'autogenerate_ns_record' parameter defaulting to 'true'
  ns1/resource_zone.go
  ns1/resource_zone_test.go
Labels: size/M

#83 docs an example for using the autogenerate_ns_record flag
  website/docs/r/zone.html.markdown
Labels: documentation, size/XS

#85 import zone autogenerate_ns_record fix
  ns1/resource_zone.go
Labels: size/XS

#86 minor refactor of testAccCheckNSRecord
  ns1/resource_zone_test.go
Labels: size/XS

#87 INBOX-341: emphasize record/regions ordering requirements
  website/docs/r/record.html.markdown
Labels: documentation, size/XS
