Repository ns1-terraform/terraform-provider-ns1, pull requests merged in 2019-12, with the labels that each got.

#96 INT-80: support URLFWD records
  go.mod
  go.sum
  ns1/resource_record.go
  ns1/resource_record_test.go
  vendor/gopkg.in/ns1/ns1-go.v2/rest/model/dns/answer.go
  vendor/gopkg.in/ns1/ns1-go.v2/rest/model/dns/dnssec.go
  vendor/gopkg.in/ns1/ns1-go.v2/rest/model/dns/record.go
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/modules.txt
Labels: dependencies, size/L

#97 records: handle zone/domain strings with leading/trailing dots
  README.md
  ns1/resource_record.go
  ns1/resource_record_test.go
  website/docs/r/record.html.markdown
Labels: documentation, size/M

#98 record: clean up the documentation for zone and domain validation
  README.md
  website/docs/r/record.html.markdown
Labels: documentation, size/S

#99 Update resource state management to properly handle disappearing resources
  go.mod
  ns1/resource_apikey.go
  ns1/resource_apikey_test.go
  ns1/resource_datafeed.go
  ns1/resource_datafeed_test.go
  ns1/resource_datasource.go
  ns1/resource_datasource_test.go
  ns1/resource_monitoringjob.go
  ns1/resource_monitoringjob_test.go
  ns1/resource_notifylist.go
  ns1/resource_notifylist_test.go
  ns1/resource_record.go
  ns1/resource_record_test.go
  ns1/resource_team.go
  ns1/resource_team_test.go
  ns1/resource_user.go
  ns1/resource_user_test.go
  ns1/resource_zone.go
  ns1/resource_zone_test.go
Labels: size/XL

#100 Clean up permission diffs on users and api keys
  ns1/permissions.go
  ns1/resource_apikey.go
  ns1/resource_apikey_test.go
  ns1/resource_team.go
  ns1/resource_team_test.go
  ns1/resource_user.go
  ns1/resource_user_test.go
  website/docs/r/apikey.html.markdown
  website/docs/r/user.html.markdown
Labels: documentation, size/XL
