Repository ns1-terraform/terraform-provider-ns1, pull requests merged in 2020-01, with the labels that each got.

#108 Update Documentation For IPv4 Only Fields
  website/docs/d/zone.html.markdown
  website/docs/r/zone.html.markdown
Labels: documentation, size/XS

#102 add a deprecation warning to short_answers
  ns1/resource_record.go
Labels: size/XS

#105 ddi permission support and ip whitelist support
  go.mod
  go.sum
  ns1/config.go
  ns1/permissions.go
  ns1/permissions_migrations.go
  ns1/provider.go
  ns1/resource_apikey.go
  ns1/resource_apikey_migrations.go
  ns1/resource_apikey_test.go
  ns1/resource_team.go
  ns1/resource_team_migrations.go
  ns1/resource_team_test.go
  ns1/resource_user.go
  ns1/resource_user_migrations.go
  ns1/resource_user_test.go
  vendor/gopkg.in/ns1/ns1-go.v2/rest/account_apikey.go
  vendor/gopkg.in/ns1/ns1-go.v2/rest/account_team.go
  vendor/gopkg.in/ns1/ns1-go.v2/rest/account_user.go
  vendor/gopkg.in/ns1/ns1-go.v2/rest/client.go
  vendor/gopkg.in/ns1/ns1-go.v2/rest/ddi.go
  vendor/gopkg.in/ns1/ns1-go.v2/rest/model/account/apikey.go
  vendor/gopkg.in/ns1/ns1-go.v2/rest/model/account/permissions.go
  vendor/gopkg.in/ns1/ns1-go.v2/rest/model/account/team.go
  vendor/gopkg.in/ns1/ns1-go.v2/rest/model/account/user.go
  vendor/gopkg.in/ns1/ns1-go.v2/rest/model/dns/answer.go
  vendor/modules.txt
  website/docs/index.html.markdown
  website/docs/r/apikey.html.markdown
  website/docs/r/team.html.markdown
  website/docs/r/user.html.markdown
Labels: dependencies, documentation, size/XXL

#109 add repo status
  README.md
Labels: size/XS

#110 release notes for 1.7.0
  CHANGELOG.md
Labels: size/XS
